import { Exercise } from '@/types';

export const strengthExercises: Exercise[] = [
  {
    id: 'squat',
    name: 'Agachamento (Squat)',
    category: 'strength',
    description: 'Agachamento básico para fortalecimento de quadríceps, glúteos e core.',
    sets: 3,
    reps: 12,
    restSeconds: 60,
    difficulty: 'iniciante',
    targetMuscles: ['Quadríceps', 'Glúteos', 'Core'],
    benefits: ['Aumenta potência para subidas', 'Melhora estabilidade do joelho', 'Fortalece cadeia posterior'],
    precautions: ['Mantenha joelhos alinhados com os pés', 'Não ultrapasse 90° se houver dor'],
  },
  {
    id: 'lunge',
    name: 'Afundo (Lunge)',
    category: 'strength',
    description: 'Afundo alternado para fortalecimento unilateral e equilíbrio.',
    sets: 3,
    reps: 10,
    restSeconds: 60,
    difficulty: 'iniciante',
    targetMuscles: ['Quadríceps', 'Glúteos', 'Isquiotibiais'],
    benefits: ['Corrige assimetrias entre pernas', 'Melhora estabilidade em corrida'],
    precautions: ['Joelho da frente não ultrapassa o pé', 'Mantenha tronco ereto'],
  },
  {
    id: 'plank',
    name: 'Prancha (Plank)',
    category: 'core',
    description: 'Prancha isométrica para fortalecimento do core e estabilidade.',
    sets: 3,
    duration: 30,
    restSeconds: 30,
    difficulty: 'iniciante',
    targetMuscles: ['Core', 'Abdômen', 'Lombar'],
    benefits: ['Melhora postura na corrida', 'Reduz oscilação do tronco', 'Aumenta eficiência energética'],
    precautions: ['Mantenha corpo alinhado', 'Não deixe quadril cair'],
  },
  {
    id: 'side-plank',
    name: 'Prancha Lateral',
    category: 'core',
    description: 'Prancha lateral para oblíquos e estabilidade lateral.',
    sets: 3,
    duration: 20,
    restSeconds: 30,
    difficulty: 'iniciante',
    targetMuscles: ['Oblíquos', 'Core lateral'],
    benefits: ['Estabiliza pelve durante corrida', 'Previne dores lombares'],
    precautions: ['Mantenha corpo em linha reta', 'Ombro alinhado com cotovelo'],
  },
  {
    id: 'clam-shell',
    name: 'Clam Shell',
    category: 'prevention',
    description: 'Ativação de glúteo médio para prevenção de lesões no joelho e quadril.',
    sets: 3,
    reps: 15,
    restSeconds: 30,
    difficulty: 'iniciante',
    targetMuscles: ['Glúteo médio', 'Abdutores'],
    benefits: ['Previne síndrome da banda iliotibial', 'Estabiliza joelho e quadril'],
    precautions: ['Mantenha pés juntos', 'Não rotate o tronco'],
  },
  {
    id: 'glute-bridge',
    name: 'Elevação de Quadril (Glute Bridge)',
    category: 'prevention',
    description: 'Ativação de glúteos para prevenção de lesões e melhora da corrida.',
    sets: 3,
    reps: 15,
    restSeconds: 45,
    difficulty: 'iniciante',
    targetMuscles: ['Glúteos', 'Isquiotibiais'],
    benefits: ['Ativa glúteos "adormecidos"', 'Previne dores no joelho'],
    precautions: ['Não hiperestenda a lombar', 'Aperte glúteos no topo'],
  },
  {
    id: 'calf-raise',
    name: 'Elevação de Panturrilha',
    category: 'strength',
    description: 'Elevação de panturrilha para fortalecimento de tornozelo e prevenção de lesões.',
    sets: 3,
    reps: 15,
    restSeconds: 45,
    difficulty: 'iniciante',
    targetMuscles: ['Panturrilha', 'Tornozelo'],
    benefits: ['Previne tendinite aquileana', 'Fortalece tornozelo'],
    precautions: ['Movimento controlado', 'Amplitude completa'],
  },
  {
    id: 'jump-squat',
    name: 'Agachamento com Salto',
    category: 'plyometric',
    description: 'Agachamento com salto para potência e economia de corrida.',
    sets: 3,
    reps: 10,
    restSeconds: 60,
    difficulty: 'intermediário',
    targetMuscles: ['Quadríceps', 'Glúteos', 'Panturrilha'],
    benefits: ['Aumenta potência', 'Melhora economia de corrida'],
    precautions: ['Aterrisse suavemente', 'Joelhos alinhados com pés'],
  },
];

export interface StrengthProgram {
  id: string;
  name: string;
  description: string;
  duration: string;
  frequency: string;
  exercises: Exercise[];
  phase: string;
}

export const strengthPrograms: StrengthProgram[] = [
  {
    id: 'base-strength',
    name: 'Fortalecimento Base',
    description: 'Programa para Fase I (Base). Foco em ativação muscular e prevenção de lesões.',
    duration: '20-30 minutos',
    frequency: '2x por semana',
    phase: 'Fase I — Base',
    exercises: [
      strengthExercises.find(e => e.id === 'squat')!,
      strengthExercises.find(e => e.id === 'lunge')!,
      strengthExercises.find(e => e.id === 'plank')!,
      strengthExercises.find(e => e.id === 'side-plank')!,
      strengthExercises.find(e => e.id === 'clam-shell')!,
      strengthExercises.find(e => e.id === 'glute-bridge')!,
      strengthExercises.find(e => e.id === 'calf-raise')!,
    ],
  },
  {
    id: 'quality-strength',
    name: 'Fortalecimento para Qualidade',
    description: 'Programa para Fases II-III. Inclui pliometria e exercícios mais avançados.',
    duration: '30-40 minutos',
    frequency: '2x por semana',
    phase: 'Fase II-III — Qualidade',
    exercises: [
      strengthExercises.find(e => e.id === 'jump-squat')!,
      strengthExercises.find(e => e.id === 'lunge')!,
      strengthExercises.find(e => e.id === 'plank')!,
      strengthExercises.find(e => e.id === 'glute-bridge')!,
      strengthExercises.find(e => e.id === 'calf-raise')!,
    ],
  },
  {
    id: 'recovery-mobility',
    name: 'Recuperação e Mobilidade',
    description: 'Sessão de mobilidade e recuperação ativa para dias de descanso.',
    duration: '15-20 minutos',
    frequency: 'Diária ou pós-treino',
    phase: 'Todas as fases',
    exercises: [
      strengthExercises.find(e => e.id === 'clam-shell')!,
      strengthExercises.find(e => e.id === 'glute-bridge')!,
      strengthExercises.find(e => e.id === 'side-plank')!,
    ],
  },
  {
    id: 'injury-prevention',
    name: 'Prevenção de Lesões',
    description: 'Programa focado em exercícios preventivos para corredores com histórico de lesões.',
    duration: '20-25 minutos',
    frequency: '3x por semana',
    phase: 'Todas as fases',
    exercises: [
      strengthExercises.find(e => e.id === 'clam-shell')!,
      strengthExercises.find(e => e.id === 'glute-bridge')!,
      strengthExercises.find(e => e.id === 'side-plank')!,
      strengthExercises.find(e => e.id === 'calf-raise')!,
    ],
  },
];
