import type { Exercise } from '@/types';

const exercise = (value: Exercise): Exercise => value;

export const strengthExercises: Exercise[] = [
  exercise({
    id: 'squat',
    name: 'Agachamento',
    category: 'strength',
    movementPattern: 'Agachar — bilateral',
    description: 'Agachamento controlado para quadríceps, glúteos e tronco.',
    sets: 3,
    reps: 8,
    restSeconds: 90,
    difficulty: 'iniciante',
    targetMuscles: ['Quadríceps', 'Glúteos', 'Core'],
    benefits: ['Melhora a produção de força', 'Aumenta a tolerância a subidas e desacelerações'],
    precautions: ['Use amplitude confortável e sem dor', 'Mantenha joelhos acompanhando a linha dos pés'],
    tempo: '3s descida — 1s pausa — subida controlada',
    loadGuidance: 'Peso corporal no início; depois use carga que deixe 2–3 repetições na reserva (RPE 7–8).',
    progression: 'Quando completar todas as séries com técnica e 2 repetições na reserva, aumente a carga em 2–5%.',
  }),
  exercise({
    id: 'split-squat',
    name: 'Agachamento dividido',
    category: 'strength',
    movementPattern: 'Unilateral — joelho dominante',
    description: 'Variação unilateral para força, controle pélvico e equilíbrio entre as pernas.',
    sets: 3,
    reps: 8,
    restSeconds: 75,
    difficulty: 'iniciante',
    targetMuscles: ['Quadríceps', 'Glúteos', 'Adutores'],
    benefits: ['Reduz diferenças entre os lados', 'Treina estabilidade em apoio único'],
    precautions: ['Comece com apoio próximo para equilíbrio', 'Não force amplitude se houver dor no joelho'],
    tempo: '2s descida — subida firme',
    loadGuidance: 'Peso corporal ou halteres leves; pare com 2–3 repetições na reserva.',
    progression: 'Aumente primeiro a amplitude e o controle; depois adicione carga em incrementos pequenos.',
  }),
  exercise({
    id: 'single-leg-rdl',
    name: 'Levantamento terra unilateral',
    category: 'strength',
    movementPattern: 'Dobradiça de quadril — unilateral',
    description: 'Fortalece a cadeia posterior e exige controle do quadril em apoio único.',
    sets: 3,
    reps: 8,
    restSeconds: 90,
    difficulty: 'intermediário',
    targetMuscles: ['Isquiotibiais', 'Glúteos', 'Lombar', 'Pé e tornozelo'],
    benefits: ['Desenvolve força posterior', 'Melhora controle do quadril durante a passada'],
    precautions: ['Mantenha coluna neutra', 'Use apoio se perder equilíbrio'],
    tempo: '3s descida — retorno controlado',
    loadGuidance: 'Comece sem carga; evolua para halter ou kettlebell com RPE 7–8.',
    progression: 'Progrida de apoio bilateral para unilateral e só então aumente a carga.',
  }),
  exercise({
    id: 'glute-bridge',
    name: 'Elevação de quadril',
    category: 'strength',
    movementPattern: 'Extensão de quadril',
    description: 'Extensão de quadril para glúteos e isquiotibiais, com progressão para carga externa.',
    sets: 3,
    reps: 10,
    restSeconds: 60,
    difficulty: 'iniciante',
    targetMuscles: ['Glúteos', 'Isquiotibiais'],
    benefits: ['Aumenta capacidade de extensão do quadril', 'Facilita a progressão para exercícios mais pesados'],
    precautions: ['Não hiperestenda a lombar', 'Mantenha costelas alinhadas com a pelve'],
    tempo: '2s subida — 2s contração no topo',
    loadGuidance: 'Peso corporal; depois use miniband ou carga sobre a pelve.',
    progression: 'Evolua para unilateral e depois para hip thrust com carga.',
  }),
  exercise({
    id: 'nordic-assisted',
    name: 'Nórdico assistido',
    category: 'strength',
    movementPattern: 'Flexão de joelho — excêntrico',
    description: 'Progressão excêntrica para isquiotibiais, com assistência suficiente para manter controle.',
    sets: 2,
    reps: 5,
    restSeconds: 120,
    difficulty: 'avançado',
    targetMuscles: ['Isquiotibiais', 'Panturrilha'],
    benefits: ['Desenvolve força excêntrica posterior', 'Complementa a força de quadríceps e glúteos'],
    precautions: ['Comece com grande assistência', 'Não avance se houver dor muscular aguda ou dor no joelho'],
    tempo: '3–5s descida; retorno assistido',
    loadGuidance: 'Use amplitude parcial e assistência com as mãos no início.',
    progression: 'Aumente gradualmente a amplitude excêntrica antes de reduzir a assistência.',
  }),
  exercise({
    id: 'calf-raise',
    name: 'Elevação de panturrilha em pé',
    category: 'strength',
    movementPattern: 'Flexão plantar — joelho estendido',
    description: 'Fortalecimento do gastrocnêmio e do complexo do tornozelo.',
    sets: 3,
    reps: 12,
    restSeconds: 60,
    difficulty: 'iniciante',
    targetMuscles: ['Gastrocnêmio', 'Tornozelo'],
    benefits: ['Aumenta a capacidade de propulsão', 'Fortalece o tornozelo para repetição de impactos'],
    precautions: ['Use amplitude completa sem dor', 'Evite quicar no final do movimento'],
    tempo: '2s subida — 2s descida',
    loadGuidance: 'Peso corporal; evolua para unilateral e depois para carga externa.',
    progression: 'Passe para unilateral quando completar 3×15 bilateral com controle.',
  }),
  exercise({
    id: 'soleus-raise',
    name: 'Elevação de panturrilha sentado',
    category: 'strength',
    movementPattern: 'Flexão plantar — joelho flexionado',
    description: 'Fortalecimento do sóleo, importante para absorção e produção repetida de força na corrida.',
    sets: 3,
    reps: 12,
    restSeconds: 60,
    difficulty: 'intermediário',
    targetMuscles: ['Sóleo', 'Tornozelo'],
    benefits: ['Complementa a elevação em pé', 'Aumenta a resistência local da panturrilha'],
    precautions: ['Comece com carga leve', 'Não treine sobre dor persistente no tendão'],
    tempo: '2s subida — 3s descida',
    loadGuidance: 'Use halter ou máquina sobre os joelhos; RPE 7–8.',
    progression: 'Aumente a carga em 2–5% quando completar todas as repetições.',
  }),
  exercise({
    id: 'tibialis-raise',
    name: 'Elevação do tibial anterior',
    category: 'prevention',
    movementPattern: 'Dorsiflexão do tornozelo',
    description: 'Fortalecimento da musculatura anterior da perna para controle do pé.',
    sets: 2,
    reps: 15,
    restSeconds: 45,
    difficulty: 'iniciante',
    targetMuscles: ['Tibial anterior', 'Tornozelo'],
    benefits: ['Melhora controle da aterrissagem', 'Equilibra o trabalho da panturrilha'],
    precautions: ['Movimente apenas o tornozelo', 'Reduza volume se houver dor na canela'],
    tempo: '2s subida — 2s descida',
    loadGuidance: 'Comece sem carga; use faixa elástica quando o movimento estiver fácil.',
    progression: 'Aumente repetições até 20 e depois a resistência da faixa.',
  }),
  exercise({
    id: 'plank',
    name: 'Prancha frontal',
    category: 'core',
    movementPattern: 'Anti-extensão do tronco',
    description: 'Estabilidade do tronco sem movimento excessivo da lombar.',
    sets: 3,
    duration: 30,
    restSeconds: 30,
    difficulty: 'iniciante',
    targetMuscles: ['Core', 'Abdômen', 'Lombar'],
    benefits: ['Melhora transmissão de força', 'Reduz compensações do tronco'],
    precautions: ['Pare antes de perder o alinhamento', 'Não deixe a lombar afundar'],
    loadGuidance: 'Use uma duração que permita respiração contínua e postura estável.',
    progression: 'Aumente até 45s; depois use variações com alavanca maior, não apenas mais tempo.',
  }),
  exercise({
    id: 'side-plank',
    name: 'Prancha lateral',
    category: 'core',
    movementPattern: 'Anti-flexão lateral',
    description: 'Estabilidade lateral da pelve e do tronco em apoio lateral.',
    sets: 3,
    duration: 20,
    restSeconds: 30,
    difficulty: 'iniciante',
    targetMuscles: ['Oblíquos', 'Glúteo médio', 'Core lateral'],
    benefits: ['Melhora controle da pelve', 'Treina estabilidade em apoio único'],
    precautions: ['Mantenha ombro afastado da orelha', 'Faça dos dois lados'],
    loadGuidance: 'Use 20–30s com alinhamento perfeito.',
    progression: 'Evolua para pernas estendidas ou abdução da perna superior.',
  }),
  exercise({
    id: 'clam-shell',
    name: 'Abdução de quadril — clam shell',
    category: 'prevention',
    movementPattern: 'Abdução e rotação externa do quadril',
    description: 'Exercício de baixa carga para controle do glúteo médio.',
    sets: 2,
    reps: 15,
    restSeconds: 30,
    difficulty: 'iniciante',
    targetMuscles: ['Glúteo médio', 'Abdutores'],
    benefits: ['Facilita consciência do alinhamento do joelho', 'Pode ser usado em ativação'],
    precautions: ['Não gire o tronco para ganhar amplitude', 'Não trate o exercício como garantia de prevenção'],
    loadGuidance: 'Miniband opcional; mantenha execução lenta.',
    progression: 'Use apenas como ativação ou evolua para abdução em apoio único.',
  }),
  exercise({
    id: 'jump-squat',
    name: 'Agachamento com salto',
    category: 'plyometric',
    movementPattern: 'Potência — bilateral',
    description: 'Pliometria simples para produção rápida de força e economia de corrida.',
    sets: 3,
    reps: 5,
    restSeconds: 90,
    difficulty: 'intermediário',
    targetMuscles: ['Quadríceps', 'Glúteos', 'Panturrilha'],
    benefits: ['Treina potência', 'Complementa força pesada e corrida rápida'],
    precautions: ['Aterrisse silenciosamente', 'Use somente sem dor e com técnica estável'],
    loadGuidance: 'Peso corporal; qualidade e altura moderada são mais importantes que fadiga.',
    progression: 'Aumente primeiro a qualidade e o descanso; depois introduza variações mais exigentes.',
  }),
  exercise({
    id: 'ankle-mobility',
    name: 'Mobilidade de tornozelo',
    category: 'mobility',
    movementPattern: 'Mobilidade — tornozelo',
    description: 'Movimento controlado para melhorar a dorsiflexão sem forçar dor.',
    duration: 45,
    restSeconds: 15,
    difficulty: 'iniciante',
    targetMuscles: ['Tornozelo', 'Panturrilha'],
    benefits: ['Melhora conforto no agachamento', 'Ajuda a manter amplitude funcional'],
    precautions: ['Não pressione a articulação com dor', 'Movimento lento e respirado'],
    progression: 'Aumente gradualmente a amplitude, não a velocidade.',
  }),
  exercise({
    id: 'hip-mobility',
    name: 'Mobilidade de quadril',
    category: 'mobility',
    movementPattern: 'Mobilidade — quadril',
    description: 'Sequência leve de mobilidade para quadril, adutores e flexores.',
    duration: 60,
    restSeconds: 15,
    difficulty: 'iniciante',
    targetMuscles: ['Quadril', 'Adutores', 'Flexores do quadril'],
    benefits: ['Reduz rigidez percebida', 'Prepara o corpo para movimentos amplos'],
    precautions: ['Não transformar mobilidade em alongamento doloroso', 'Respire sem prender o ar'],
    progression: 'Aumente a amplitude apenas mantendo controle e conforto.',
  }),
];

export interface StrengthProgram {
  id: string;
  name: string;
  description: string;
  duration: string;
  frequency: string;
  exercises: Exercise[];
  phase: string;
  goal: 'base' | 'quality' | 'power' | 'taper' | 'recovery' | 'prevention';
  guidance: string;
}

const byId = (id: string) => {
  const found = strengthExercises.find((item) => item.id === id);
  if (!found) throw new Error(`Exercício de força não encontrado: ${id}`);
  return found;
};

export const strengthPrograms: StrengthProgram[] = [
  {
    id: 'base-strength',
    name: 'Força Base',
    description: 'Sessão geral para construir capacidade técnica e força básica sem competir com a corrida.',
    duration: '25–35 minutos',
    frequency: '2x por semana',
    phase: 'Fase I — Base',
    goal: 'base',
    guidance: 'Faça em dias E, preferencialmente depois da corrida ou separado por várias horas. Termine sentindo que conseguiria fazer mais 2–3 repetições.',
    exercises: [byId('squat'), byId('split-squat'), byId('glute-bridge'), byId('calf-raise'), byId('soleus-raise'), byId('plank'), byId('side-plank')],
  },
  {
    id: 'quality-strength',
    name: 'Força e Cadeia Posterior',
    description: 'Sessão de força com ênfase em dobradiça de quadril, unilateral, panturrilha e core.',
    duration: '30–40 minutos',
    frequency: '2x por semana',
    phase: 'Fases II–III — Qualidade',
    goal: 'quality',
    guidance: 'Mantenha pelo menos 24 horas entre esta sessão e o treino I mais exigente. Não busque falha muscular.',
    exercises: [byId('single-leg-rdl'), byId('split-squat'), byId('nordic-assisted'), byId('calf-raise'), byId('soleus-raise'), byId('side-plank')],
  },
  {
    id: 'power-maintenance',
    name: 'Potência e Manutenção',
    description: 'Baixo volume de potência e força para preservar adaptação sem gerar fadiga excessiva.',
    duration: '20–30 minutos',
    frequency: '1–2x por semana',
    phase: 'Fase III — Transição',
    goal: 'power',
    guidance: 'Faça descansos completos e interrompa a série quando a velocidade ou a aterrissagem piorarem.',
    exercises: [byId('jump-squat'), byId('squat'), byId('single-leg-rdl'), byId('calf-raise'), byId('plank')],
  },
  {
    id: 'taper-maintenance',
    name: 'Manutenção no Polimento',
    description: 'Sessão curta para manter coordenação e força, sem criar dano muscular antes da prova.',
    duration: '15–20 minutos',
    frequency: '1x por semana',
    phase: 'Fase IV — Polimento',
    goal: 'taper',
    guidance: 'Reduza uma série de cada exercício e mantenha pelo menos 3 repetições na reserva. Não introduza exercícios novos.',
    exercises: [byId('split-squat'), byId('glute-bridge'), byId('calf-raise'), byId('side-plank')],
  },
  {
    id: 'recovery-mobility',
    name: 'Mobilidade e Recuperação',
    description: 'Rotina leve de mobilidade e ativação para dias de descanso ou após treinos fáceis.',
    duration: '10–15 minutos',
    frequency: 'Conforme necessidade',
    phase: 'Todas as fases',
    goal: 'recovery',
    guidance: 'A sessão deve reduzir rigidez percebida, nunca aumentar dor ou fadiga.',
    exercises: [byId('ankle-mobility'), byId('hip-mobility'), byId('clam-shell'), byId('glute-bridge')],
  },
  {
    id: 'injury-prevention',
    name: 'Acessórios de Prevenção',
    description: 'Acessórios para tornozelo, quadril e controle lateral, sem promessa de eliminar lesões.',
    duration: '15–20 minutos',
    frequency: '2–3x por semana',
    phase: 'Todas as fases',
    goal: 'prevention',
    guidance: 'Use como complemento, não como substituto de avaliação profissional ou de uma sessão de força completa.',
    exercises: [byId('calf-raise'), byId('soleus-raise'), byId('tibialis-raise'), byId('side-plank'), byId('clam-shell')],
  },
];

export function getStrengthProgram(programId: string): StrengthProgram {
  return strengthPrograms.find((program) => program.id === programId) ?? strengthPrograms[0];
}

export function getStrengthProgramForPhase(phase: number, isTaper = false): StrengthProgram {
  if (isTaper) return getStrengthProgram('taper-maintenance');
  if (phase <= 1) return getStrengthProgram('base-strength');
  if (phase === 2) return getStrengthProgram('quality-strength');
  if (phase === 3) return getStrengthProgram('power-maintenance');
  return getStrengthProgram('quality-strength');
}
